### ISSUE TITLE
Missing ZDR

### ISSUE THREAD

**Issue by jdiasn** [actris-cloudnet/rpgpy#11]
I have been using the rpgpy to convert the binary files from full polarimetric radars (35 GHz and 94 GHz), and I noticed that the Differential Reflectivity is missing (ZDR) in the NetCDF files. I used another converting tool to generate the NetCDF from the same binary file as a crosscheck. After the conversion,  I saw that the ZDR is present in the new NetCDF file.

**Comment by tukiains** [comment]
Can you provide an example file so I can investigate?

**Comment by jdiasn** [comment]
Here you are a file example.

[BaseN_210913_001152_P01_PPI.LV1.nc.zip](https://github.com/actris-cloudnet/rpgpy/files/7250856/BaseN_210913_001152_P01_PPI.LV1.nc.zip)

**Comment by tukiains** [comment]
I believe it's the variable named `ldr` which RPG manual calls `RefRat`..? It's a little confusing because different names are used in different places. I'm not sure if there is any standard naming convention. Hmm, maybe there should be at least a comment in each variable explaining these a little better.

**Comment by jdiasn** [comment]
I compared the LDR (from rpg2nc output) with the ZDR (from my previous converting tool ), and they are the same. ZDR (differential reflectivity ratio) and LDR (linear depolarisation ratio) are different radars variables and their names are well defined in the radar literature. I suggest updating the variable name from ldr to zdr and its long_name to the differential reflectivity ratio.

The variable ldr_slanted and its attributes are correct (they should not be modified).

**Comment by tukiains** [comment]
OK thanks for noticing this, I will fix it according to your suggestion.

**Comment by tukiains** [comment]
There is now a PR about this: https://github.com/actris-cloudnet/rpgpy/pull/12

**Comment by tukiains** [comment]
Fixed in v0.10.0.
