### ISSUE TITLE
Indexing error in the converted lv0 files

### ISSUE THREAD

**Issue by martin-rdz** [actris-cloudnet/rpgpy#16]
@ti-vo, @KarlJohnsonnn and me found a discrepancy in the lv0 files between rpgpy and the rpg conversion routine.
So far we have only detected that issue in the files from Punta Arenas (with a rather early version of the radar software).
We could not pin down the problem, but a brief check by Alexander indicates, that there is an indexing error in the rpgpy binary reading routine.

To illustrate the issue (Total and H spectrum are available in the respective files, V spectrum is calculated):
<img src="https://user-images.githubusercontent.com/31452472/153706563-1686e39b-ce95-43af-a0f8-de14f3c4529f.png" width="500">
<img src="https://user-images.githubusercontent.com/31452472/153706564-0af60d66-6ceb-48d2-8308-2ba001eba951.png" width="500">

But the problem also occurs at other ranges and timesteps.
The data of the example is available [here](https://owncloud.gwdg.de/index.php/s/rQ3WoC27R244oen) (link will expire).

Any insights are highly appreciated.
Best,
Martin

**Comment by tukiains** [comment]
Thanks for reporting this issue and providing example data. I will take a look at it.

**Comment by tukiains** [comment]
Hmm, I can't reproduce this discrepancy.. at least when I quickly tried it. Example code:

```
import netCDF4
import numpy as np
from rpgpy import rpg2nc

fpath = f'/home/tukiains/Downloads/rpgpy_problem/'

rpg2nc(f'{fpath}*.LV0', 'output.nc')

nc = netCDF4.Dataset('output.nc')
data = nc.variables['doppler_spectrum_h'][:]
nc.close()

nc = netCDF4.Dataset(f'{fpath}190911_030001_P05_ZEN.LV0.NC')
data_refe = nc.variables['C1HSpec'][:]
nc.close()

diffu = data[:, :37, :] - data_refe

print(np.max(diffu))
print(np.min(diffu))

0.0
0.0
```

However, I do see difference between the example rpgpy netCDF file from you and the one generated by me above. Did you run rpgpy with the latest version and did you try different machines?

**Comment by martin-rdz** [comment]
To prevent similar problems in future it would be nice, if the version number of rpgpy that processed a particular output file could be added to the output netcdfs global attributes.

**Comment by tukiains** [comment]
I agree, this would be useful information. I can add it.
