### ISSUE TITLE
read_prg does not load vertical polarization data

### ISSUE THREAD

**Issue by jabravoaranda** [actris-cloudnet/rpgpy#22]
read_rpg provides 'HSpec', linked to horizontal polarization but 'VSpec', linked to vertical polarization, is omitted. This variable is also specified in the RPG software documentation (https://www.radiometer-physics.de/download/PDF/Cloud%20Radar/RPG-FMCW-Operation%20and%20SW_Manual.pdf). Could you add this variable in the next version? It would be so helpful. 

Documentation: 
- VSpec_1[n]     float 4 x SpecN     full Doppler spectrum (incl. noise), vertical pol., linear Ze

**Comment by siiptuo** [comment]
There are many versions of the radar and file format and, unfortunately, the newer documentation is not publicly available. It seems that `VSpec` was changed to `TotSpec` in the file format version 3.5:

> The total spectrum is identical to the vertical polarisation spectrum for single polarized or LDR-mode radars. In the case of dual polarized STSR-mode radars, this spectrum represents the combined spectrum given in equation (2.11.13).

There is [some code](https://github.com/actris-cloudnet/rpgpy/blob/58bc00585b676d585d8210853f38eaaa657c7bfa/rpgpy/spcutil.py#L167-L168) in rpgpy related to the dual polarized STSR-mode radars.

**Comment by jabravoaranda** [comment]
Thanks for the update. I will try to use the code you mention.
